# Generated by Django 6.0.1 on 2026-01-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project/')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': "Project's",
            },
        ),
    ]
